### ISSUE TITLE
Ошибка запуска после обновлений от 24.05.2017

### ISSUE THREAD

**Issue by dkoviazin** [dkoviazin/jetcalc#89]
Шувалов Петр. 25.05.2017

Не открывается основное окно. В консоле клиента выдается ошибка

Refused to execute script from 'https://assoi2.ugmk.com/build/lib.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

P.S.
Так же после комита 3cb4157. При старте приложения в консоле сервера появляется ошибка:
```bash
{ Error: ENOENT: no such file or directory, open '/htdocs/ugmk/static/build/index.html'
4|ugmk     |     at Error (native)
4|ugmk     |     at Object.fs.openSync (fs.js:640:18)
4|ugmk     |     at Object.fs.writeFileSync (fs.js:1333:33)
4|ugmk     |     at /htdocs/ugmk/modules/modules/compiller.js:93:16
4|ugmk     |     at /htdocs/ugmk/node_modules/async/dist/async.js:484:16
4|ugmk     |     at iteratorCallback (/htdocs/ugmk/node_modules/async/dist/async.js:1084:13)
4|ugmk     |     at /htdocs/ugmk/node_modules/async/dist/async.js:988:16
4|ugmk     |     at /htdocs/ugmk/modules/modules/compiller.js:90:24
4|ugmk     |     at /htdocs/ugmk/modules/modules/compiller.js:134:20
4|ugmk     |     at /htdocs/ugmk/modules/modules/compiller.js:149:24
4|ugmk     |     at /htdocs/ugmk/node_modules/async/dist/async.js:484:16
4|ugmk     |     at iteratorCallback (/htdocs/ugmk/node_modules/async/dist/async.js:1084:13)
4|ugmk     |     at /htdocs/ugmk/node_modules/async/dist/async.js:988:16
4|ugmk     |     at /htdocs/ugmk/modules/modules/compiller.js:146:28
4|ugmk     |     at FSReqWrap.oncomplete (fs.js:123:15)
4|ugmk     |   errno: -2,
4|ugmk     |   code: 'ENOENT',
4|ugmk     |   syscall: 'open',
4|ugmk     |   path: '/htdocs/ugmk/static/build/index.html' } undefined
```

Лечится созданием папки static/build/ и файла index.html из проекта они были исключены.

**Comment by dkoviazin** [comment]
**Ковязин Дмитрий**. 25.05.2017

Понял в чем могла быть проблема
я удалил из гита собранные библиотеки
чтобы они собрались нужно запустить в консоле grunt

**Comment by dkoviazin** [comment]
**Ковязин Дмитрий**. 25.05.2017

Дубликат CA-42

**Comment by dkoviazin** [comment]
Нужно после установки системы запустить grunt
